services:
  database:
    image: mysql:8.4
    container_name: connexie-database
    env_file: .env
    volumes:
      - /app/database
    ports:
      - 3306:3306

  api:
    build: ./
    container_name: connexie-api
    env_file: .env
    environment:
      - DATABASE_URL=mysql://root:root@database:3306/connexie

    depends_on:
      - database
    volumes:
      - ./:/app/backend
      - /app/backend/node_modules
    ports:
      - 3001:3001
