services:
  database:
    image: mysql:8.4
    container_name: connexie-database
    env_file: .env
    volumes:
      - /app/database
      - ./src/infrastructure/database/init/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  api:
    build: ./
    container_name: connexie-api
    env_file: .env
    depends_on:
      - database
    volumes:
      - ./:/app/backend
      - /app/backend/node_modules
    ports:
      - 3001:3001
